#!/usr/bin/env python
import socket
import sys
import json
import musc

HOST = 'localhost'
PORT = musc.config.PORT
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

s.sendall(json.dumps({'args':sys.argv}))
data = s.recv(1024)
s.close()
print 'Received', repr(data)
