#!/usr/bin/env python
import socket

HOST = 'localhost'
PORT = 7785 #port number (mu in ascii) 
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.sendall('Hello, world')
data = s.recv(1024)
s.close()
print 'Received', repr(data)
