#!/usr/bin/env python
import socket
import musc

server = musc.network.Server()
HOST = ''
PORT = musc.config.PORT
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)
while True:
    conn, addr = s.accept()
    print 'Connected by', addr
    while 1:
        data = conn.recv(1024)
        if not data: break
        if server.doAction(data): #use data as the arbguments
            conn.sendall('OK')
        else:
            conn.sendall('ERROR')
        print 'data start:', data, 'data end'
    conn.close()
